export enum TokenType {
    NUMBER, WORD,
    TEXT,

    PLUS, MINUS,
    STAR, SLASH,
    EXP,

    ASSIGN, EQUAL, NOT_EQUAL,
    LT, GT,
    LTEQUAL, GTEQUAL,
    EXCL,
    
    BAR, BARBAR,
    AMP, AMPAMP,

    LPAREN, RPAREN,
    LBRACE, RBRACE,
    SEMICOLON, COMMA,

    KW_IF, KW_ELSE,
    KW_FOR, KW_WHILE,
    KW_DO, KW_BREAK, KW_CONTINUE,
    KW_VOID, KW_RETURN,
    KW_IMPORT,

    EOF
}